config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   resources :authors
   root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  helper :hot_glue
  include HotGlue::ControllerHelper

  
  
  before_action :load_author, only: [:show, :edit, :update, :destroy]
  after_action -> { flash.discard }, if: -> { request.format.symbol ==  :turbo_stream }
 
  def load_author
    @author = (Author.find(params[:id]))
  end
  

  def load_all_authors 
    @authors = ( Author.page(params[:page]))  
  end

  def index
    load_all_authors
  end

  def new 
    @author = Author.new()
   
  end

  def create
    modified_params = modify_date_inputs_on_params(author_params.dup)


    @author = Author.create(modified_params)

    if @author.save
      flash[:notice] = "Successfully created #{@author.name}"
      load_all_authors
      render :create
    else
      flash[:alert] = "Oops, your author could not be created. #{@hawk_alarm}"
      render :create, status: :unprocessable_entity
    end
  end


  def edit
    render :edit
  end

  def update
    modified_params = modify_date_inputs_on_params(author_params)
      

    if @author.update(modified_params)
      
      flash[:notice] = (flash[:notice] || "") << "Saved #{@author.name}"
      flash[:alert] = @hawk_alarm if @hawk_alarm
      render :update
    else
      flash[:alert] = (flash[:alert] || "") << "Author could not be saved. #{@hawk_alarm}"
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      @author.destroy
    rescue StandardError => e
      flash[:alert] = "Author could not be deleted."
    end
    load_all_authors
  end

  def author_params
    params.require(:author).permit( [:name] )
  end

  def namespace
    ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="bg-blue-900 text-center py-4 lg:px-4"><div class="p-2 bg-blue-800 items-center text-blue-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert"><span class="flex rounded-full bg-blue-500 uppercase font-bold px-2 py-1 text-xs mr-3">New</span><span class="font-semibold mr-2 text-left flex-auto">Hello Tailwind</span></div></div>

app/views/authors/_errors.erb
<%= turbo_frame_tag "errors" do %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/authors/_form.erb
<div class="row">
  <div class='' >  
    <span class='<%= "alert-danger" if author.errors.details.keys.include?(:name) %>'  style="display: inherit;"  >
        <%= f.text_field :name, value: author.name, autocomplete: 'off', size: 40, class: 'form-control', type: '' %>
       
      
      <label class='small form-text text-muted'>Name</label>
    </span>
    <br />
  </div>

  <div class="">
    <%= link_to "Cancel", authors_path,  {class: "btn btn-secondary"} %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/authors/_line.erb
<%= turbo_frame_tag "__#{ dom_id(author) }" do  %>
  <div class='grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700' data-id='<%= author.id %>' data-edit='false'>
    <%= render partial: 'authors/show', locals: { author: author } %>

  </div>
<% end %>

app/views/authors/_list.erb
<%= turbo_frame_tag "__authors-list"   do %>
  <div class=" overflow-x-auto w-full">
    
      <h4>
        AUTHORS
      </h4>
    

    <%= render partial: "authors/new_button", locals: {} %><br />

    
      
        <div class="grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700 grid grid-cols-4 gap-x-16 p-4 text-sm font-medium text-gray-900 bg-gray-100 border-t border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700 dark:text-white">
          <div class=''>Name</div>
          

          <div class=' scaffold-col-heading scaffold-col-heading-buttons ' >
          </div>
        </div>
      

      <% if authors.empty? %>
    <div>
        None
    </div>
      <% end %>
      <% authors.each do |author| %>
        <%= render partial: 'authors/line', locals: {author: author}
            .merge(defined?(nested_for) ? {nested_for: nested_for} : {})
      
        %>
      <% end %>
    <% if authors.respond_to?(:total_pages) %><%= paginate(authors) %> <% end %>
  
  </div>
<% end %>

app/views/authors/_new_button.erb
<%= turbo_frame_tag "__author-new" do %>
  <div>
    <%= link_to "New AUTHOR",  new_author_path, disable_with: "Loading...", class: "new-author-button btn btn-primary pull-right  " %>
  </div>
<% end %>

app/views/authors/_new_form.erb
<%= turbo_frame_tag "__author-new" do %>
<h3>
  New AUTHOR
  </h3>
  <%= form_with model:  author, url: authors_path, method: :post do  |f| %>
    <%=  render partial: "authors/form",
      locals: { author: author, f: f} %>
  <% end %>
<% end %>

app/views/authors/_show.erb
<div class=''><%= author.name %></div>




<div class=" scaffold-line-buttons " >
  

  
    <%= form_with url: author_path(author), html: {data: {'turbo-confirm': "Are you sure you want to delete #{ author.name }?"}, style: "display: inline-block;"}, method: :delete do |f| %>
      <%= f.submit "Delete".html_safe,  class: "delete-author-button btn btn-primary btn-sm" %>
    <% end %>
  

  
  <%= link_to "Edit <i class='fa fa-1x fa-list-alt'></i>".html_safe, edit_author_path(author), disable_with: "Loading...", class: "edit-author-button btn btn-primary btn-sm" %>
  
</div>

app/views/authors/create.turbo_stream.erb
<% if @author.errors.none? %>
  <%= turbo_stream.replace "__authors-list" + "" do %>
  <%= render partial: "list", locals: {authors: @authors} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "__author__author-new" do %>
  <% if @author.errors.none? %>
  <%= render partial: "new_button", locals: {} %>
  <% else %>
  <%= render partial: "new_form", locals: {author: @author} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @author.errors.any? %>
  <%= render partial: "errors", locals: {resource: @author} %>
  <% end %>
<% end %>

app/views/authors/destroy.turbo_stream.erb
<%= turbo_stream.replace "__authors-list" + "" do %>
  <%= render partial: "list", locals: {authors: @authors } %>
<% end %>

app/views/authors/edit.erb
<%= link_to "<i class='fa fa-arrow-circle-left  2x'></i> Back to list".html_safe, authors_path %>

<%= turbo_frame_tag "__#{dom_id(@author)}" do  %>

  <div class="cell editable" style="position: relative;">

    <% if @author.errors.any? %>
      <%= render(partial: "errors", locals: {resource: @author }) %>
    <% end %>

    <h2>Editing <%= @author.name %></h2>
    <%= form_with model: @author, url: author_path(@author) do |f| %>
    <%=  render partial: "form",  locals: {:author => @author, f: f} %>
    <% end %>

  </div>

<% end %>

app/views/authors/edit.turbo_stream.erb
<%= turbo_stream.replace "__#{dom_id(author)}" do %>
  <%= render 'edit' %>
<% end %>

app/views/authors/index.erb
<div class="bg-blue-900 text-center py-4 lg:px-4"><div class="p-2 bg-blue-800 items-center text-blue-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert"><span class="flex rounded-full bg-blue-500 uppercase font-bold px-2 py-1 text-xs mr-3">New</span><span class="font-semibold mr-2 text-left flex-auto">Hello Tailwind</span></div></div>


<div class="">
  <div class="overflow-hidden min-w-max"> 

  <%= render partial: 'authors/list',
    locals: {authors: @authors} %>

  </div> 
</div>



<div id="detailed-pricing" class="overflow-x-auto w-full">
  <div class="overflow-hidden min-w-max">
    <div class="grid grid-cols-4 gap-x-16 p-4 text-sm font-medium text-gray-900 bg-gray-100 border-t border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700 dark:text-white">
      <div class="flex items-center">Tailwind CSS code</div>
      <div>Community Edition</div>
      <div>Developer Edition</div>
      <div>Designer Edition</div>
    </div>
    <div class="grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700">
      <div class="text-gray-500 dark:text-gray-400">Basic components (<a href="#" class="text-blue-600 hover:underline">view all</a>)</div>
      <div>
        <svg class="w-5 h-5 text-green-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-green-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-green-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
    </div>
    <div class="grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700">
      <div class="text-gray-500 dark:text-gray-400">Application UI (<a href="#" class="text-blue-600 hover:underline">view demo</a>)</div>
      <div>
        <svg class="w-5 h-5 text-red-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-green-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-red-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
    </div>
    <div class="grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700">
      <div class="text-gray-500 dark:text-gray-400">Marketing UI pre-order</div>
      <div>
        <svg class="w-5 h-5 text-red-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-green-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-red-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
    </div>
    <div class="grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700">
      <div class="text-gray-500 dark:text-gray-400">E-commerce UI pre-order</div>
      <div>
        <svg class="w-5 h-5 text-red-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-green-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      </div>
      <div>
        <svg class="w-5 h-5 text-red-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </div>
    </div>
    <div class="grid grid-cols-4 gap-x-16 py-5 px-4 text-sm text-gray-700 border-b border-gray-200 dark:border-gray-700">
      <div class="text-gray-500 dark:text-gray-400"></div>
      <div>
        <a href="#" class="text-white block w-full bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-200 font-medium rounded-lg text-sm px-4 py-2.5 text-center dark:focus:ring-blue-900">Buy now</a>
      </div>
      <div>
        <a href="#" class="text-white block w-full bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-200 font-medium rounded-lg text-sm px-4 py-2.5 text-center dark:focus:ring-blue-900">Buy now</a>
      </div>
      <div>
        <a href="#" class="text-white block w-full bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-200 font-medium rounded-lg text-sm px-4 py-2.5 text-center dark:focus:ring-blue-900">Buy now</a>
      </div>
    </div>
  </div>
</div>

app/views/authors/new.erb
<%= render partial: "new_form", locals: {author: @author} %>

app/views/authors/update.turbo_stream.erb
<%= turbo_stream.replace "__#{dom_id(@author)}" do %>
  <%= render partial: 'line', locals: {author: @author } %>
<% end %>

<%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @author.errors.any? %>
  <%= render partial: "errors", locals: {resource: @author} %>
  <% end %>
<% end %>

app/views/layouts/_flash_notices.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? %>
    <div class="alert alert-notice alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible">
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTailwind5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <%= render partial: 'layouts/flash_notices' %>
  
    <%= yield %>
  </body>
</html>